// CSWebsiteBuilder/src/app/schedule/schedule.component.ts
import { Component, OnInit } from '@angular/core';
import { WebsiteConfig } from '../models/WebsiteConfig';
import { Resource } from '../models/Resource';

@Component({
  selector: 'app-schedule',
  templateUrl: './schedule.component.html',
  styleUrls: ['./schedule.component.css']
})
export class ScheduleComponent implements OnInit {

  config:WebsiteConfig

  constructor() { }

  ngOnInit() {
    this.config = new WebsiteConfig();
  }

  isDownloadable(resource:Resource): boolean{
    if (resource.avaliableDate < new Date()){
      return true;
    }
    return false;
  }
}

<h1>Schedule</h1>
<hr>
<p>On this page you can find links to the assignments for each class this semester.</p>
<br>
<div *ngFor="let class of config.classValues">
    <span class="float-right">{{class.date | date}}</span>
    <h2>{{class.title}}</h2>
    <p></p>
    <table class="table table-hover" *ngIf="class.resources.length > 0">
        <thead>
            <th>Assignment Name</th>
            <th>Download Link</th>
        </thead>
        <tbody id="table_body">
            <tr *ngFor="let resource of class.resources">
              <td>{{resource.title}}</td>
              <td *ngIf="this.isDownloadable(resource)"><a href="#">Download</a></td>
              <td *ngIf="!this.isDownloadable(resource)"><a title="Not avaliable until {{resource.avaliableDate | date}}" href="#">Not Avaliable</a></td>
            </tr>
        </tbody>
    </table>
    <br>
</div>

// cs-website-builder/src/builderTemplates/Schedule.jsx
import React, { Component } from 'react';
import { Head } from '../helperComponents/Head.jsx';
import { Header } from '../helperComponents/Header.jsx';
import { FileBuilder } from '../FileBuilder.jsx';

export class Schedule extends Component {

    renderAssignment(assignment) {
        const config = this.props.config;
        const filePath = `${config.baseURL}${assignment.bodyReference.filePath}`;
        return (
            <tr key={assignment}>
                <td>{assignment.title}</td>
                <td>
                    {
                        assignment.availableDate <= new Date() ?
                            <a href={filePath} role="button" className="btn btn-byu float-right">View</a> :
                            <a href="#" role="button" className="btn btn-byu float-right disabled" disabled>Not Avalivable</a>
                    }
                </td>
            </tr>
        )
    }

    renderClassNote(classNote) {
        const config = this.props.config;
        const filePath = `${config.baseURL}${classNote.fileReference.filePath}`;
        return (
            <tr key={classNote}>
                <td>{classNote.title}</td>
                <td>
                    {
                        classNote.availableDate <= new Date() ?
                            <a target="_blank" href={filePath} role="button" className="btn btn-byu float-right">Download</a> :
                            <a href="#" role="button" className="btn btn-byu float-right disabled" disabled>Not Avalivable</a>
                    }
                </td>
            </tr>
        )
    }

    renderClass(classPeriod) {

        if (classPeriod.classNotes.length == 0 && classPeriod.assignments.length == 0){
            return (<span key={classPeriod}></span>);
        }

        return (
            <div key={classPeriod}>
                <span className="float-right">{classPeriod.date.toDateString()}</span>
                <h2>{classPeriod.title}</h2>
                <table className="table table-hover">
                    {classPeriod.classNotes.map((classNote) => this.renderClassNote(classNote))}
                    {classPeriod.assignments.map((assignment) => this.renderAssignment(assignment))}
                </table>
                <br />
            </div>
        )
    }

    render() {
        const config = this.props.config;

        return (
            <html>
                <Head />
                <Header config={config} baseURL={''} />
                <div className="Schedule container content">
                    <h1>Schedule</h1>
                    <hr />
                    <p>On this page you can find links to the class notes and assignments for this semester.</p>
                    <br />
                    {
                        config.classPeriods.map((classPeriod) => this.renderClass(classPeriod))
                    }
                </div>
            </html>
        );
    }
}
